[package]
org = "jian_cloete"
name = "ticketing_service"
version = "0.1.0"
distribution = "2201.12.9"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "postgresql"
version = "1.14.0"

[[dependency]]
org = "ballerinax"
name = "postgresql.driver"
version = "1.6.0"

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "3.7.0"
